version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: dormdeal-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dormdeal
    volumes:
      - mongodb_data:/data/db
    networks:
      - dormdeal-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dormdeal-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URL: mongodb://admin:password123@mongodb:27017/dormdeal?authSource=admin
      BASE_URL: http://localhost:5173
      # Add your other environment variables here
      # JWT_SECRET: your_jwt_secret
      # CLOUDINARY_CLOUD_NAME: your_cloudinary_name
      # CLOUDINARY_API_KEY: your_cloudinary_key
      # CLOUDINARY_API_SECRET: your_cloudinary_secret
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - dormdeal-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dormdeal-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - dormdeal-network

  # Redis for session management (optional)
  redis:
    image: redis:7-alpine
    container_name: dormdeal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dormdeal-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  dormdeal-network:
    driver: bridge