version: '3.8'

services:
  backend:
    image: yanakorns/dormdeals-project:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dormdeal-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      BASE_URL: "http://localhost:5173"
      DB_URL: "mongodb+srv://YanakornS:0924077286Yan@cluster0.1adb7.mongodb.net/dormdeals"
      SECRET: "dormdeals-jwt"

      # 🔹 Firebase config
      FIREBASE_TYPE: "service_account"
      FIREBASE_PROJECT_ID: "loykratongse-85138"
      FIREBASE_PRIVATE_KEY_ID: "9068f41863fdce142a00aa2f10f5cecd3795db38"
      FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGSqnaR0v5/tto\n5KN/kUpm6xu853nLT390VYwdm0VidAn0ztQ2X32cWt6xm0P2g062qDachk0Bmrh5\ni4AV5m2PdW61U70GbyWYHC7+aUupu+9uhfzOKO8lA6N87c76plxj2wWJrd0BSzgh\nYiF9JFhsAMjkFpmXiVdnS50JGjvE1H5XVuGBcg0q/aF3PFF2WROtQ5dxEiL8iSfd\nMFngZunKGJU1+vsiUw7sS+KfECJbeoJrZcwgSUfw38/PflSGls8zO9fO/ct/YHw1\nzN8vEhimDw5G/Q15CQ1jgEn5RyN/uB5D96TQu5sC0oBfhIBatT8A2CRuPjiPHc7n\niqXE9W1bAgMBAAECggEAB0o+bKPp7tcw22KZO6lyXmXRv3hmNqudC0ZGDsdRo8HX\njd0zH3Rw00bisg22IXBlwh3R4lnsYdc3wr2lENHHr0jU6lrfXGmyIOdy5e+mQvjq\ngpoeLtCBz7exkuD/3KC9B3NVEEnIwJRJ3a3IxJYVQqrfzyKJwJOzAFSB6m1Ybi8o\nRev688zP2jrlkteBHfRf4oxl33QBj95V6RG10o4Vagq+jYZehGmdtTxJ8nRY42EL\noaPXyv0WRUcAClQKSpcZQ2mcQE5gbD1oxFbgNEqFnjwAdGVx2lmO1boe//8lK0TV\n5Kctk4/e8SWogSmq6hikc25E86njBWRK1xCbcrzLNQKBgQDmLHL/CqOFMv+DFsMT\nHfs7smeronLdcxtIb1wLx5oL1Q2C+4jRnu/LIZ7lgiTBiyxTTbAYlIZVfXLdA4H2\nI3q7sBbTNn/KimemVdwDrn36vnZXuqNXpUqNKsLFhYwgjmiQgzBqXKETfQqif7lX\nyYrO/dsp8uCCtYa0jgsmQeqMZwKBgQDcim4uugoy0bxGK9BFhri0XsMXUpy12gke\nNrEnEfASqIzrCDPnn2n5iKf3RbeaUH5aVddu6C2VwdpVPcVpAgmoSky6ewhoqL2s\nN7ZhpQXBkfrh8WP3RSHUdlJedv1Rb9DGePXHt27kPQcC7liWpxwrvjdU90BjzNOF\nJqYB7lu+7QKBgQC0/zkCgwwo/vxbyfdmPgpEXDsXhWvL5esLX75C6ReivEuet0tU\ngyXPV0XK9jcPFvCpJQsXmRu1eCttzodQ1X96vbKFLnL5AzMUYqnbH0ijd0g6HmK5\n1hm0vm5gwm55X2KsWO0mhmaHm6lUNRm7BZoowQipiPqw7ivaKWRtFiJpewKBgAWV\nL4LZTMbKjmSMWWJZLbXLLE8b1UG5Oj/cjJF7n8MpJyAP/hhf7bPWZMIarrImVXx9\n7c0t7XF8DcXYoXWuCoaLEvQphyX3F44Tfvdr0QB8bIhprukkg923/Q/NHU6BcRyF\nFVuv5gu7C8FkPTPbGRh2YToyZBvipHwbZVppKUNlAoGABA7jecweu2Q64CrNy3lS\nA6OURnQ9QHdXd+RG2C7vVVHqk5ynKv7BXdpXPioR5dEd24nCootVGVxBs/JvDjuF\nzANHCL47jY0ZS0a0kltge+64ZwZngE6JMTpNZO8ZBWJCuP4OztU/5HHVekLIIpWa\nULaPfYOmqqx7xLwpt6elUOw=\n-----END PRIVATE KEY-----\n"
      FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-4t0ct@loykratongse-85138.iam.gserviceaccount.com"

      # 🔹 Cloudinary & PromptPay
      CLOUDINARY_CLOUD_NAME: "duytgvohc"
      CLOUDINARY_API_KEY: "572125628685289"
      CLOUDINARY_API_SECRET: "EoWUXw1Td_HkvSilEMxwpQMwhZA"

      REQUIREDAMOUNT_PROMPTPAY_QR: "110"
      EXPECTEDNAMEENG_PROMPTPAY_QR: "MR. ANGKAN B"
      EASYSLIP_API_KEY: "876968cd-d643-473b-b438-078bafcf1a45"

    networks:
      - dormdeal-network

  frontend:
    image: yanakorns/dormdeals-project:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_APIKEY: ${VITE_APIKEY}
        VITE_AUTHDOMAIN: ${VITE_AUTHDOMAIN}
        VITE_PROJECTID: ${VITE_PROJECTID}
        VITE_STORAGEBUCKET: ${VITE_STORAGEBUCKET}
        VITE_MESSAGINGSENDERID: ${VITE_MESSAGINGSENDERID}
        VITE_APPID: ${VITE_APPID}
        VITE_MEASUREMENTID: ${VITE_MEASUREMENTID}
        VITE_BASE_URL: ${VITE_BASE_URL}
    container_name: dormdeal-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - dormdeal-network

networks:
  dormdeal-network:
    driver: bridge
